# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth1', '0002_remove_employees_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='department_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
